# Create a Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventmanager-pv
  namespace: eventmanager
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
  mountOptions:
    - hard
    # Mount using NFS v 4.1
    - nfsvers=4.1
  nfs:
    # The path in the NAS
    path: "/path/to/folder"
    # The NAS IP
    server: <NFS Server IP>
    # Make sure to allow to write
    readOnly: false