# Create a Persistent Volume Claim for the pod to access the directory

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventmanager-pv-claim
  namespace: eventmanager
spec:
  storageClassName: ""
  # Name of the volume to tie to this claim
  volumeName: eventmanager-pv
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem  
  resources:
    requests:
      storage: 1Gi